### ISSUE TITLE
Switch to a Spring Boot standalone application with runnable fat JAR

### ISSUE THREAD

**Issue by tkrille** [osiam/addon-self-administration#133]
This is the umbrella issue for the transition of this component to a Spring Boot standalone application with an executable fat JAR. See also osiam/osiam#5 for the initial reasons and discussion.

Tasks that have to be done:

- [x] Switch from xml to java configuration (#72)
- [x] Introduce Spring Boot, but keep WAR deployment (#124)
- [ ] Switch to YAML configration (#134)
- [ ] Switch to standalone application (#135 / PR: #127)

Please, maintain this list, if you add new issues or close existing ones.

**Comment by dacrome** [comment]
I updated the issue description, the last point is already more or less done in [this PR](https://github.com/osiam/addon-self-administration/pull/127)

**Comment by tkrille** [comment]
Obsoleted by osiam/osiam#158
